source("loadData.R")
png(filename = "plot3.png", width = 480, height = 480, units = "px", res=72, bg = "white")
plot(c(1,2880),c(1,40),ylab="Energy sub-metering",type="n",xlab="",xaxt="n",yaxt="n")
axis(1,at=c(1,1440,2880),labels=c("Thu","Fri","Sat"))
axis(2,at=c(0,10,20,30))
lines(twoDays$Sub_metering_1)
lines(twoDays$Sub_metering_2,col="red")
lines(twoDays$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1))
dev.off()
